;/*FB_PKG_DELIM*/

__d("AddOnStartOverride.react",["react","react-compiler-runtime","stylex"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||d("react");function a(a){var b=d("react-compiler-runtime").c(10),e,f,g;b[0]!==a?(e=a.ref,g=a.xstyle,f=babelHelpers.objectWithoutPropertiesLoose(a,["ref","xstyle"]),b[0]=a,b[1]=e,b[2]=f,b[3]=g):(e=b[1],f=b[2],g=b[3]);b[4]!==g?(a=(h||(h=c("stylex"))).props(g),b[4]=g,b[5]=a):a=b[5];b[6]!==e||b[7]!==f||b[8]!==a?(g=j.jsx("div",babelHelpers["extends"]({},f,{ref:e},a)),b[6]=e,b[7]=f,b[8]=a,b[9]=g):g=b[9];return g}g["default"]=a}),98);
__d("BaseList.react",["CometCompositeStructureContext","CometFocusGroup.react","focusScopeQueries","react","react-compiler-runtime","react-strict-dom"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));h.useMemo;function a(a){var b=d("react-compiler-runtime").c(26),e=a["aria-label"],f=a["aria-labelledby"],g=a.children,h=a.keyNavOrientation_DEPRECATED,j=a.ref,k=a.role,l=a.testid,m=a.variant,n=a.xstyle;a=(a=k)!=null?a:"list";var o;b[0]!==a?(o={role:a},b[0]=a,b[1]=o):o=b[1];o=o;o=o;if(h!=null){var p;if(b[2]!==e||b[3]!==f||b[4]!==g||b[5]!==k||b[6]!==(m==null?void 0:(p=m.xstyleConfig)==null?void 0:p.root)||b[7]!==n){var q;p=function(a){var b;return i.jsx(d("react-strict-dom").html.div,{"aria-label":(b=e)!=null?b:void 0,"aria-labelledby":f,ref:j,role:(b=k)!=null?b:void 0,style:[a,n,m==null?void 0:(b=m.xstyleConfig)==null?void 0:b.root],children:g})};b[2]=e;b[3]=f;b[4]=g;b[5]=k;b[6]=m==null?void 0:(q=m.xstyleConfig)==null?void 0:q.root;b[7]=n;b[8]=p}else p=b[8];b[9]!==h||b[10]!==k||b[11]!==p?(q=i.jsx(c("CometFocusGroup.react"),{orientation:h,role:k,tabScopeQuery:d("focusScopeQueries").tabbableScopeQuery,children:p}),b[9]=h,b[10]=k,b[11]=p,b[12]=q):q=b[12];return q}p=(h=e)!=null?h:void 0;h=m==null?void 0:(q=m.xstyleConfig)==null?void 0:q.root;b[13]!==h||b[14]!==n?(q=[n,h],b[13]=h,b[14]=n,b[15]=q):q=b[15];b[16]!==g||b[17]!==o?(h=i.jsx(c("CometCompositeStructureContext").Provider,{value:o,children:g}),b[16]=g,b[17]=o,b[18]=h):h=b[18];b[19]!==f||b[20]!==a||b[21]!==p||b[22]!==q||b[23]!==h||b[24]!==l?(o=i.jsx(d("react-strict-dom").html.div,{"aria-label":p,"aria-labelledby":f,"data-testid":void 0,ref:j,role:a,style:q,children:h}),b[19]=f,b[20]=a,b[21]=p,b[22]=q,b[23]=h,b[24]=l,b[25]=o):o=b[25];return o}g["default"]=a}),98);
__d("CometList_DEPRECATED.react",["BaseList.react","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react"),j={margins:{marginBottom:"x1oo3vh0",marginTop:"x1rdy4ex",$$css:!0}};function a(a){var b=d("react-compiler-runtime").c(12),e=a.children,f=a.items,g=a.keyNavOrientation_DEPRECATED,h=a.label,k=a.ref,l=a.role,m=a.testid;a=a.withNegativeMargins;if(b[0]!==e||b[1]!==f){var n;n=typeof e==="function"?((n=f)!=null?n:[]).map(function(a,b){if(a==null||typeof a!=="object")return null;if(a.key==null)return e({item:a,key:b});a.key;b=babelHelpers.objectWithoutPropertiesLoose(a,["key"]);return e({item:b,key:a.key})}):e;b[0]=e;b[1]=f;b[2]=n}else n=b[2];f=n;b[3]!==g||b[4]!==h||b[5]!==l||b[6]!==m?(n={"aria-label":h,keyNavOrientation_DEPRECATED:g,role:l,testid:m},b[3]=g,b[4]=h,b[5]=l,b[6]=m,b[7]=n):n=b[7];g=n;h=a&&j.margins;b[8]!==g||b[9]!==f||b[10]!==h?(l=i.jsx(c("BaseList.react"),babelHelpers["extends"]({},g,{ref:k,xstyle:h,children:f})),b[8]=g,b[9]=f,b[10]=h,b[11]=l):l=b[11];return l}g["default"]=a}),98);
__d("FDSCautionTriangleFilled16Icon",["cr:13969"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:13969")}),98);
__d("FDSCautionTriangleFilled16PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("502061"),16);b=a;g["default"]=b}),98);
__d("FDSChevronLeftFilled24Icon",["cr:13979"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:13979")}),98);
__d("FDSChevronLeftFilled24PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("492491"),24);b=a;g["default"]=b}),98);
__d("FDSChevronRightFilled24Icon",["cr:13867"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:13867")}),98);
__d("FDSChevronRightFilled24PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("492539"),24);b=a;g["default"]=b}),98);
__d("FDSHouseFilled20Icon",["cr:15139"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15139")}),98);
__d("FDSHouseFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("481926"),20);b=a;g["default"]=b}),98);
__d("FDSPlusFilled16Icon",["cr:14064"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14064")}),98);
__d("FDSPlusFilled16PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("483768"),16);b=a;g["default"]=b}),98);
__d("FDSSettingsFilled20Icon",["cr:14083"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14083")}),98);
__d("FDSSettingsFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("497567"),20);b=a;g["default"]=b}),98);
__d("FDSStarFilled20Icon",["cr:15698"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15698")}),98);
__d("FDSStarFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("479327"),20);b=a;g["default"]=b}),98);
__d("XCometAccountStatusRootControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/account_status/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);